# Generated by Django 3.1 on 2020-09-16 14:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('package_type', models.CharField(blank=True, choices=[('SMALL', 'SMALL'), ('MEDIUM', 'MEDIUM'), ('LARGE', 'LARGE'), ('NONE', 'NONE')], default='NONE', max_length=8)),
                ('telephone', models.CharField(default='[]', max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='measure_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('kWhr', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='meters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('meter_type', models.CharField(blank=True, choices=[('VSPP', 'VSPP'), ('CUSTOMER', 'CUSTOMER'), ('GRID', 'GRID')], default='CUSTOMER', max_length=8)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sub_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('area_no', models.CharField(blank=True, max_length=3, null=True)),
                ('area_text', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='time_slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('text_time', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('vspp_value', models.FloatField(blank=True)),
                ('grid_value', models.FloatField(blank=True)),
                ('kWhr', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mymeter.measure_data')),
                ('meter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymeter.meters')),
                ('t_slot', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mymeter.time_slot')),
            ],
        ),
        migrations.AddField(
            model_name='meters',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mymeter.sub_area'),
        ),
        migrations.AddField(
            model_name='meters',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymeter.accounts'),
        ),
        migrations.AddField(
            model_name='measure_data',
            name='meter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymeter.meters'),
        ),
        migrations.AddField(
            model_name='measure_data',
            name='t_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymeter.time_slot'),
        ),
    ]
