# Generated by Django 3.1 on 2020-09-11 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymeter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('vspp_value', models.FloatField(blank=True)),
                ('grid_value', models.FloatField(blank=True)),
                ('kWhr', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mymeter.measure_data')),
                ('meter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymeter.meters')),
                ('t_slot', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mymeter.time_slot')),
            ],
        ),
    ]
