# Generated by Django 3.1 on 2020-08-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymeter', '0003_auto_20200818_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='meters',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
