# Generated by Django 3.1 on 2020-09-15 01:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymeter', '0003_auto_20200915_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_slot',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
